In [1]:
x={'name':"Nidhi","Email":"xcvb@gmail.com","age":23}

In [2]:
x

{'name': 'Nidhi', 'Email': 'xcvb@gmail.com', 'age': 23}

In [3]:
for i in x:
    print(i)

name
Email
age


In [4]:
for i in x:
    print(x[i])

Nidhi
xcvb@gmail.com
23


In [5]:
for i in x.values():
    print(i)

Nidhi
xcvb@gmail.com
23


In [6]:
for i in x.keys():
    print(i)

name
Email
age


In [7]:
for i in x.keys():
    print(x[i])


Nidhi
xcvb@gmail.com
23


In [8]:
x={"n","gmail","MSIS"}


In [9]:
fname,email,College=x


In [10]:
x


{'MSIS', 'gmail', 'n'}

In [11]:
fname

'gmail'

In [12]:
sales_Record={'price':3,'num_items':4,'person':"nidhi","email":"nidhi@gmail.com"}


In [13]:
statement='{} bought {} item at price of INR {} each for a total of INR {}'


In [14]:
print(statement.format(sales_Record['person'],sales_Record['num_items'],sales_Record['price'],sales_Record['num_items']*sales_Record['price']))


nidhi bought 4 item at price of INR 3 each for a total of INR 12


In [15]:
import datetime as dt

In [16]:
import time as tm

In [17]:
tm.time()

1699985012.3668895

In [18]:
from datetime import date,timedelta
from datetime import time
from datetime import datetime

In [19]:
today=date.today()

In [20]:
print(today)

2023-11-14


In [21]:
dtnow=dt.datetime.fromtimestamp(tm.time())

In [22]:
dtnow

datetime.datetime(2023, 11, 14, 18, 3, 32, 395177)

In [23]:
today=datetime.now()

In [24]:
previousdays=today-timedelta(days=100)

In [25]:
print(previousdays.date())

2023-08-06


In [26]:
class Person:
    institution="MSIS, Manipal"

    def enter_name(self,new_name):
        self.name=new_name
    def enter_age(self,new_age):
        self.age=new_age

In [27]:
s=Person()
s.enter_name("Nidhi")
s.enter_age(23)

In [28]:
s={1,2,3,1,7,4}

In [29]:
t=(4,5,6)

In [30]:
s

{1, 2, 3, 4, 7}

In [31]:
t


(4, 5, 6)

In [32]:
s.add(8)


In [33]:
s

{1, 2, 3, 4, 7, 8}

In [34]:
store1 = [10.00,11.00,12.4,5.34]

store2 = [19.00, 10.10,12.34,5.01]

store3 = [15.00 , 12.00,11.00,6.00]

cheapest = map(min,store1, store2, store3)

costly = map(max ,  store1 , store2 , store3)

In [35]:
print(cheapest)

#this will give us the memory location

In [36]:
for item in cheapest:
    print(item)

10.0
10.1
11.0
5.01


In [37]:
def calculateSquare(n):
    return n*n

calculateSquare(4)

16

In [38]:
numbers = (1,2,3,4)

result = map(calculateSquare, numbers)

print(result)

In [39]:
res = list(result)
print(res)

[1, 4, 9, 16]


In [40]:
n1=[4,5,6]
n2=[5,6,7]

In [41]:
result=map(lambda a,b:a+b,n1,n2)

In [42]:
list(result)

[9, 11, 13]

In [43]:
s="Python programming language"
print(s.split()[0])

Python


In [44]:
people=["Python programming language","Computer lab test","msis manipal college"]


In [45]:
def split_title(person):
    title=person.split()[0]
    lastname=person.split()[-1]
    return '{} {}'.format(title,lastname)

In [46]:
list(map(split_title,people))

['Python language', 'Computer test', 'msis college']

In [47]:
#Iterate 0 to 200 to print odd numbers
for i in range(201):
    if(i%2!=0):
        print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99
101
103
105
107
109
111
113
115
117
119
121
123
125
127
129
131
133
135
137
139
141
143
145
147
149
151
153
155
157
159
161
163
165
167
169
171
173
175
177
179
181
183
185
187
189
191
193
195
197
199


In [48]:
import numpy as np

In [49]:
x=[1,2,3,4]
y=np.array(x)

In [50]:
y.shape

(4,)

In [51]:
lspace=np.linspace(0,10,9)

In [52]:
lspace

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [53]:
p=np.ones([3,2])

In [54]:
p


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
np.vstack([p,2*p])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [2., 2.]])

In [56]:
np.hstack([p,2*p])

array([[1., 1., 2., 2.],
       [1., 1., 2., 2.],
       [1., 1., 2., 2.]])

In [57]:
numbers = [1, 2, 3, 4, 5]

double = lambda x: x * 2
doubled_numbers = map(double, numbers)
doubled_numbers_list = list(doubled_numbers)

print(doubled_numbers_list)

[2, 4, 6, 8, 10]


In [58]:
# Define a lambda function with three parameters, but only use the first two
my_lambda = lambda x, y, z: x + y
result = my_lambda(10, 20, 30)

print(result)

30
